/* Q1. LIST COUNTRIES WITH INCOME LEVEL OF "UPPER MIDDLE INCOME". */
SELECT NAME AS COUNTRY_NAME
FROM COUNTRY
WHERE ILEVEL_ID =
    (SELECT ID
     FROM ILEVEL
     WHERE VALUE = 'Upper middle income');
