/* Q2. LIST COUNTRIES WITH INCOME LEVEL OF "LOW INCOME" PER REGION. */
SELECT REGION.VALUE AS REGION_NAME,
       NAME AS COUNTRY_NAME
FROM COUNTRY
LEFT JOIN REGION ON (COUNTRY.REG_ID = REGION.ID)
WHERE ILEVEL_ID =
    (SELECT ID
     FROM ILEVEL
     WHERE VALUE = 'Low income')
ORDER BY REGION;
