/* Q3. FIND THE REGION WITH THE HIGHEST PROPORTION OF "HIGH INCOME" COUNTRIES. */
 WITH PROPORTIONS AS
  (SELECT REG_ID,
          ILEVEL_ID,
          COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY REG_ID) AS RATIO
   FROM COUNTRY
   GROUP BY REG_ID,
            ILEVEL_ID)
SELECT REGION.VALUE AS NAME,
       PROPORTIONS.RATIO
FROM PROPORTIONS
JOIN REGION ON REGION.ID = PROPORTIONS.REG_ID
WHERE ILEVEL_ID = 'HIC' -- Hardcoding the High income code, but that could be retrieved via a nested query too
ORDER BY RATIO DESC FETCH FIRST 1 ROW ONLY;
