/* Q4. Calculate cumulative/running value of GDP per region ordered by income from lowest to highest and country name. */
WITH INCLEV AS (
    SELECT
        ID,
        CASE ID WHEN 'LIC' THEN 1 WHEN 'LMC' THEN 2 WHEN 'UMC' THEN 3 WHEN 'HIC' THEN 4 END AS INC_RANK,
        VALUE AS LV_NAME
    FROM ILEVEL
    WHERE ID <> 'NA'
)
SELECT
    COUNTRY.NAME,
    REGION.VALUE,
    INCLEV.LV_NAME,
    NULLIF(GDP.VALUE,'')::DECIMAL AS GDP,
    SUM(NULLIF(GDP.VALUE,'')::DECIMAL) OVER (PARTITION BY COUNTRY.REG_ID ORDER BY INCLEV.INC_RANK, COUNTRY.NAME) AS RUNNING_GDP
FROM
    COUNTRY
JOIN
    GDPDATAPOINT AS GDP
ON
    (GDP.YEAR = '2017' AND GDP.CTRY_CODE = COUNTRY.ISO3)
JOIN INCLEV
ON INCLEV.ID = COUNTRY.ILEVEL_ID
JOIN REGION
ON REGION.ID = COUNTRY.REG_ID;
