/* Q7. Provide an interesting fact from the dataset. */
SELECT 
	REGION.VALUE AS REGION, 
	QUANTILE(NULLIF(GDP.VALUE,'')::FLOAT,0.5)/AVG(NULLIF(GDP.VALUE,'')::FLOAT) AS MEDIAN_TO_AVG_GDP, -- this query uses the QUANTILE extension from PGXN
	STDDEV_SAMP(NULLIF(GDP.VALUE,'')::FLOAT)/AVG(NULLIF(GDP.VALUE,'')::FLOAT) AS STDEV_TO_AVG_GDP
FROM
	GDPDATAPOINT AS GDP
LEFT JOIN COUNTRY ON (COUNTRY.ISO3 = GDP.CTRY_CODE AND GDP.YEAR = '2017')
LEFT JOIN REGION ON (REGION.ID = COUNTRY.REG_ID)
WHERE COUNTRY.REG_ID <> 'NA'
GROUP BY REGION
ORDER BY MEDIAN_TO_AVG_GDP DESC, STDEV_TO_AVG_GDP DESC;